root: true
extends:
  - actano-base

rules:
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - 'test/**/*.js'
  import/prefer-default-export:
    - off

overrides:
  - files:
      - 'test/**/*.js'
    env:
      mocha: true
