language: node_js
node_js:
- '8'
cache: yarn
script:
- npm run ci
deploy:
  provider: npm
  skip_cleanup: true
  email: rplan-ci@actano.de
  on:
    tags: true
    repo: actano/rplan-express-schema-validation-middleware
    node: '8'
  api_key:
    secure: hpQrzrLt3xOg+Ru5EIZ/9LrjBlQ0pd5D9l3A0rWXfUCCIwb0eQIqvhFvKebzPmb6MRmQZkmBhn2faFSUiJ5NHo6SooPefMLOSds8c9OrswowrCZE+U5WqwGGZRswxtt0rimzf48IBrBpsxzNT8AMJKMjo25yS1u53bzwM/12rIjCl9sdzhYUeZH556kwu7HrboOwPINVRbBzMEfHsoziQeTrlMknq7maR0OQqdZgkpXpFGBnnpXlgMwM9dyGxJD4n/vqTEGDg3fdt+M/4f7X0Oz+qf3IKHIle3ho270VgNz7aSPHOEsa3c7x5RNuJ3kl02cXAtN9wWow5Y+1LzgVAvHcmO02mqQYBqHHZw6+hi3Je0ue2/DqKsGWGqfB/n/+Nj/sa3ItnBICUkr2Fu61mocSB5zXqcyy18CU69fn8wmB25d/pQ2KOQOVDb6paODusarIc7yCbCfEW8CsWWVG3jQ+MyAsmApuuUq/XX3kZEsSGQIhhjeJ7/0dGrmh5GrfFX+oChwqxYnjjHVHy/KPogQ1XT6HfgNeN7kvZwME+4jptCRh1y1zn/3It461fFIGQcSuboluOkv8VN1FOYA4+y69DwZZkevWQg95TVtrKFcavwmshJZ6y5DhSlE6kXveTNzgE/lK/fsVnkrvJ3MLF8kQgf9DXjY4jp0/cMD21oI=
